default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: books_development

test:
  <<: *default
  database: books_test


  production:
    adapter: postgresql
    encoding: unicode
    pool: 5
    timeout: 5000
    username: "books"
    password: "password"
    database: "books"
    host:   "/cloudsql/manifest-chain-281123:us-central1:rails-database-instance"
